2024-02-19 00:07:08,910 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 00:07:08,910 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Configure stats pid to 25856
2024-02-19 00:07:08,911 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-19 00:07:08,911 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-19 00:07:08,911 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-19 00:07:08,911 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 00:07:08,912 INFO    MainThread:25856 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_000708-u48ms535\logs\debug.log
2024-02-19 00:07:08,912 INFO    MainThread:25856 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_000708-u48ms535\logs\debug-internal.log
2024-02-19 00:07:08,912 INFO    MainThread:25856 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000246F7F552A0>
2024-02-19 00:07:08,912 INFO    MainThread:25856 [wandb_init.py:init():566] calling init triggers
2024-02-19 00:07:08,912 INFO    MainThread:25856 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 10, 'max_depth': 1}
2024-02-19 00:07:08,913 INFO    MainThread:25856 [wandb_init.py:init():591] re-initializing run, found existing run on stack: m5qgqcib
2024-02-19 00:07:08,914 INFO    MainThread:25856 [wandb_run.py:_finish():1970] finishing run mc0c0z/DecisionTree/m5qgqcib
2024-02-19 00:07:08,914 INFO    MainThread:25856 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 00:07:08,915 INFO    MainThread:25856 [wandb_run.py:_restore():2193] restore
2024-02-19 00:07:08,915 INFO    MainThread:25856 [wandb_run.py:_restore():2199] restore done
2024-02-19 00:07:12,316 INFO    MainThread:25856 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 00:07:12,316 INFO    MainThread:25856 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 00:07:12,321 INFO    MainThread:25856 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-19 00:07:12,423 INFO    MainThread:25856 [wandb_init.py:init():616] starting backend
2024-02-19 00:07:12,424 INFO    MainThread:25856 [wandb_init.py:init():620] setting up manager
2024-02-19 00:07:12,425 INFO    MainThread:25856 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-19 00:07:12,427 INFO    MainThread:25856 [wandb_init.py:init():628] backend started and connected
2024-02-19 00:07:12,435 INFO    MainThread:25856 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-19 00:07:12,435 INFO    MainThread:25856 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-19 00:07:12,435 INFO    MainThread:25856 [wandb_init.py:init():720] updated telemetry
2024-02-19 00:07:12,437 INFO    MainThread:25856 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-19 00:07:13,891 INFO    MainThread:25856 [wandb_run.py:_on_init():2262] communicating current version
2024-02-19 00:07:14,068 INFO    MainThread:25856 [wandb_run.py:_on_init():2271] got version response 
2024-02-19 00:07:14,069 INFO    MainThread:25856 [wandb_init.py:init():804] starting run threads in backend
2024-02-19 00:07:14,150 INFO    MainThread:25856 [wandb_run.py:_console_start():2241] atexit reg
2024-02-19 00:07:14,151 INFO    MainThread:25856 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-19 00:07:14,151 INFO    MainThread:25856 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-19 00:07:14,151 INFO    MainThread:25856 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-19 00:07:14,151 INFO    MainThread:25856 [wandb_init.py:init():847] run started, returning control to user process
2024-02-19 00:07:21,409 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-19 00:07:21,409 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Configure stats pid to 25856
2024-02-19 00:07:21,410 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-19 00:07:21,410 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-19 00:07:21,410 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-19 00:07:21,410 INFO    MainThread:25856 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-19 00:07:21,411 INFO    MainThread:25856 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_000721-cx2hc24x\logs\debug.log
2024-02-19 00:07:21,411 INFO    MainThread:25856 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_000721-cx2hc24x\logs\debug-internal.log
2024-02-19 00:07:21,411 INFO    MainThread:25856 [wandb_init.py:init():566] calling init triggers
2024-02-19 00:07:21,411 INFO    MainThread:25856 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 10, 'max_depth': 6}
2024-02-19 00:07:21,412 INFO    MainThread:25856 [wandb_init.py:init():591] re-initializing run, found existing run on stack: u48ms535
2024-02-19 00:07:21,413 INFO    MainThread:25856 [wandb_run.py:_finish():1970] finishing run mc0c0z/DecisionTree/u48ms535
2024-02-19 00:07:21,414 INFO    MainThread:25856 [jupyter.py:save_history():445] not saving jupyter history
2024-02-19 00:07:21,414 INFO    MainThread:25856 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-19 00:07:21,414 INFO    MainThread:25856 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-19 00:07:21,414 INFO    MainThread:25856 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-19 00:07:21,414 INFO    MainThread:25856 [wandb_run.py:_restore():2193] restore
2024-02-19 00:07:21,415 INFO    MainThread:25856 [wandb_run.py:_restore():2199] restore done
2024-02-19 00:07:24,776 INFO    MainThread:25856 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-19 00:07:24,777 INFO    MainThread:25856 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-19 00:07:24,783 INFO    MainThread:25856 [wandb_run.py:_footer_sync_info():3825] logging synced files
