2024-02-18 23:37:55,605 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-18 23:37:55,605 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Configure stats pid to 28164
2024-02-18 23:37:55,605 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-18 23:37:55,605 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-18 23:37:55,606 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-18 23:37:55,606 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-18 23:37:55,606 INFO    MainThread:28164 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240218_233755-1n9m5cqd\logs\debug.log
2024-02-18 23:37:55,606 INFO    MainThread:28164 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240218_233755-1n9m5cqd\logs\debug-internal.log
2024-02-18 23:37:55,607 INFO    MainThread:28164 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002DD765DEDD0>
2024-02-18 23:37:55,607 INFO    MainThread:28164 [wandb_init.py:init():566] calling init triggers
2024-02-18 23:37:55,607 INFO    MainThread:28164 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 2, 'max_depth': 11}
2024-02-18 23:37:55,608 INFO    MainThread:28164 [wandb_init.py:init():591] re-initializing run, found existing run on stack: v1m73670
2024-02-18 23:37:55,609 INFO    MainThread:28164 [wandb_run.py:_finish():1962] finishing run mc0c0z/DecisionTree/v1m73670
2024-02-18 23:37:55,611 INFO    MainThread:28164 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-18 23:37:55,611 INFO    MainThread:28164 [wandb_run.py:_restore():2185] restore
2024-02-18 23:37:55,611 INFO    MainThread:28164 [wandb_run.py:_restore():2191] restore done
2024-02-18 23:38:03,824 INFO    MainThread:28164 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-18 23:38:03,824 INFO    MainThread:28164 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-18 23:38:03,830 INFO    MainThread:28164 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-02-18 23:38:03,921 INFO    MainThread:28164 [wandb_init.py:init():616] starting backend
2024-02-18 23:38:03,922 INFO    MainThread:28164 [wandb_init.py:init():620] setting up manager
2024-02-18 23:38:03,923 INFO    MainThread:28164 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-18 23:38:03,924 INFO    MainThread:28164 [wandb_init.py:init():628] backend started and connected
2024-02-18 23:38:03,931 INFO    MainThread:28164 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-18 23:38:03,931 INFO    MainThread:28164 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-18 23:38:03,932 INFO    MainThread:28164 [wandb_init.py:init():720] updated telemetry
2024-02-18 23:38:03,933 INFO    MainThread:28164 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-18 23:38:05,457 INFO    MainThread:28164 [wandb_run.py:_on_init():2254] communicating current version
2024-02-18 23:38:05,652 INFO    MainThread:28164 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-18 23:38:05,652 INFO    MainThread:28164 [wandb_init.py:init():804] starting run threads in backend
2024-02-18 23:38:05,748 INFO    MainThread:28164 [wandb_run.py:_console_start():2233] atexit reg
2024-02-18 23:38:05,748 INFO    MainThread:28164 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-02-18 23:38:05,748 INFO    MainThread:28164 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-02-18 23:38:05,748 INFO    MainThread:28164 [wandb_run.py:_redirect():2178] Redirects installed.
2024-02-18 23:38:05,749 INFO    MainThread:28164 [wandb_init.py:init():847] run started, returning control to user process
2024-02-18 23:38:05,749 INFO    MainThread:28164 [wandb_run.py:_config_callback():1342] config_cb None None {'min_samples': 2, 'max_depth': 11}
2024-02-18 23:38:32,028 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-18 23:38:32,028 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Configure stats pid to 28164
2024-02-18 23:38:32,028 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-18 23:38:32,029 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-18 23:38:32,029 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-18 23:38:32,029 INFO    MainThread:28164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-18 23:38:32,029 INFO    MainThread:28164 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240218_233832-fibi3y8t\logs\debug.log
2024-02-18 23:38:32,030 INFO    MainThread:28164 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240218_233832-fibi3y8t\logs\debug-internal.log
2024-02-18 23:38:32,030 INFO    MainThread:28164 [wandb_init.py:init():566] calling init triggers
2024-02-18 23:38:32,030 INFO    MainThread:28164 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'min_samples': 2, 'max_depth': 16}
2024-02-18 23:38:32,030 INFO    MainThread:28164 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 1n9m5cqd
2024-02-18 23:38:32,032 INFO    MainThread:28164 [wandb_run.py:_finish():1962] finishing run mc0c0z/DecisionTree/1n9m5cqd
2024-02-18 23:38:32,032 INFO    MainThread:28164 [jupyter.py:save_history():445] not saving jupyter history
2024-02-18 23:38:32,032 INFO    MainThread:28164 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-18 23:38:32,033 INFO    MainThread:28164 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-18 23:38:32,033 INFO    MainThread:28164 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-18 23:38:32,033 INFO    MainThread:28164 [wandb_run.py:_restore():2185] restore
2024-02-18 23:38:32,033 INFO    MainThread:28164 [wandb_run.py:_restore():2191] restore done
2024-02-18 23:38:35,738 INFO    MainThread:28164 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-18 23:38:35,738 INFO    MainThread:28164 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-18 23:38:35,745 INFO    MainThread:28164 [wandb_run.py:_footer_sync_info():3816] logging synced files
