2024-02-19 10:20:56,644 INFO    StreamThr :19076 [internal.py:wandb_internal():86] W&B internal server running at pid: 19076, started at: 2024-02-19 10:20:56.644883
2024-02-19 10:20:56,644 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: status
2024-02-19 10:20:56,644 INFO    WriterThread:19076 [datastore.py:open_for_write():87] open: d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_102051-s2mo6pjk\run-s2mo6pjk.wandb
2024-02-19 10:20:56,644 DEBUG   SenderThread:19076 [sender.py:send():382] send: header
2024-02-19 10:20:56,644 DEBUG   SenderThread:19076 [sender.py:send():382] send: run
2024-02-19 10:20:57,245 INFO    SenderThread:19076 [dir_watcher.py:__init__():211] watching files in: d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_102051-s2mo6pjk\files
2024-02-19 10:20:57,245 INFO    SenderThread:19076 [sender.py:_start_run_threads():1136] run started: s2mo6pjk with start time 1708312855.75333
2024-02-19 10:20:57,258 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: check_version
2024-02-19 10:20:57,258 DEBUG   SenderThread:19076 [sender.py:send_request():409] send_request: check_version
2024-02-19 10:20:57,684 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: run_start
2024-02-19 10:20:57,698 DEBUG   HandlerThread:19076 [system_info.py:__init__():27] System info init
2024-02-19 10:20:57,698 DEBUG   HandlerThread:19076 [system_info.py:__init__():42] System info init done
2024-02-19 10:20:57,698 INFO    HandlerThread:19076 [system_monitor.py:start():194] Starting system monitor
2024-02-19 10:20:57,698 INFO    SystemMonitor:19076 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-02-19 10:20:57,698 INFO    HandlerThread:19076 [system_monitor.py:probe():214] Collecting system info
2024-02-19 10:20:57,711 INFO    SystemMonitor:19076 [interfaces.py:start():190] Started cpu monitoring
2024-02-19 10:20:57,711 DEBUG   HandlerThread:19076 [system_info.py:probe():151] Probing system
2024-02-19 10:20:57,711 INFO    SystemMonitor:19076 [interfaces.py:start():190] Started disk monitoring
2024-02-19 10:20:57,711 INFO    SystemMonitor:19076 [interfaces.py:start():190] Started gpu monitoring
2024-02-19 10:20:57,724 INFO    SystemMonitor:19076 [interfaces.py:start():190] Started memory monitoring
2024-02-19 10:20:57,752 INFO    SystemMonitor:19076 [interfaces.py:start():190] Started network monitoring
2024-02-19 10:20:57,753 DEBUG   HandlerThread:19076 [gitlib.py:_init_repo():56] git repository is invalid
2024-02-19 10:20:57,753 DEBUG   HandlerThread:19076 [system_info.py:probe():199] Probing system done
2024-02-19 10:20:57,753 DEBUG   HandlerThread:19076 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.10.10', 'heartbeatAt': '2024-02-19T03:20:57.711681', 'startedAt': '2024-02-19T03:20:51.855537', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'host': 'Manh-PC', 'username': 'Manh Bui', 'executable': 'f:\\test\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 3301.0, 'min': 0.0, 'max': 3301.0}, 'cpu_freq_per_core': [{'current': 3301.0, 'min': 0.0, 'max': 3301.0}], 'disk': {'/': {'total': 931.5116882324219, 'used': 25.65606689453125}}, 'gpu': 'NVIDIA GeForce GTX 1650', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1650', 'memory_total': 4294967296}], 'memory': {'total': 15.355525970458984}}
2024-02-19 10:20:57,753 INFO    HandlerThread:19076 [system_monitor.py:probe():224] Finished collecting system info
2024-02-19 10:20:57,753 INFO    HandlerThread:19076 [system_monitor.py:probe():227] Publishing system info
2024-02-19 10:20:57,753 DEBUG   HandlerThread:19076 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-02-19 10:20:57,753 ERROR   HandlerThread:19076 [system_info.py:_save_conda():219] Error saving conda packages: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "f:\test\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 215, in _save_conda
    subprocess.call(
  File "f:\test\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "f:\test\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "f:\test\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2024-02-19 10:20:57,753 DEBUG   HandlerThread:19076 [system_info.py:_save_conda():220] Saving conda packages done
2024-02-19 10:20:57,753 INFO    HandlerThread:19076 [system_monitor.py:probe():229] Finished publishing system info
2024-02-19 10:20:57,753 DEBUG   SenderThread:19076 [sender.py:send():382] send: files
2024-02-19 10:20:57,753 INFO    SenderThread:19076 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-02-19 10:20:57,765 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: python_packages
2024-02-19 10:20:57,765 DEBUG   SenderThread:19076 [sender.py:send_request():409] send_request: python_packages
2024-02-19 10:20:57,805 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: stop_status
2024-02-19 10:20:57,805 DEBUG   SenderThread:19076 [sender.py:send_request():409] send_request: stop_status
2024-02-19 10:20:57,805 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-19 10:20:58,180 DEBUG   SenderThread:19076 [sender.py:send():382] send: telemetry
2024-02-19 10:20:58,258 INFO    Thread-245:19076 [dir_watcher.py:_on_file_created():271] file/dir created: d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_102051-s2mo6pjk\files\conda-environment.yaml
2024-02-19 10:20:58,258 INFO    Thread-245:19076 [dir_watcher.py:_on_file_created():271] file/dir created: d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_102051-s2mo6pjk\files\requirements.txt
2024-02-19 10:20:58,258 INFO    Thread-245:19076 [dir_watcher.py:_on_file_created():271] file/dir created: d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240219_102051-s2mo6pjk\files\wandb-metadata.json
2024-02-19 10:20:58,565 INFO    wandb-upload_0:19076 [upload_job.py:push():131] Uploaded file C:\Users\bdm2k\AppData\Local\Temp\tmpe4_rajf9wandb\rnkww7cy-wandb-metadata.json
2024-02-19 10:21:02,220 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: status_report
2024-02-19 10:21:07,248 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: status_report
2024-02-19 10:21:12,257 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: status_report
2024-02-19 10:21:12,836 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: internal_messages
2024-02-19 10:21:12,837 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: stop_status
2024-02-19 10:21:12,837 DEBUG   SenderThread:19076 [sender.py:send_request():409] send_request: stop_status
2024-02-19 10:21:18,199 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: status_report
2024-02-19 10:21:23,243 DEBUG   HandlerThread:19076 [handler.py:handle_request():146] handle_request: status_report
2024-02-19 10:21:25,941 INFO    cpu       :19076 [interfaces.py:monitor():140] Process cpu has exited.
2024-02-19 10:21:25,942 DEBUG   SystemMonitor:19076 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-02-19 10:21:25,942 DEBUG   SystemMonitor:19076 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-02-19 10:21:25,942 DEBUG   SystemMonitor:19076 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-02-19 10:21:25,964 DEBUG   SenderThread:19076 [sender.py:send():382] send: stats
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,003 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
2024-02-19 10:21:27,005 INFO    MainThread:19076 [internal.py:handle_exit():76] Internal process exited
