2024-02-21 16:38:16,442 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-21 16:38:16,442 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Configure stats pid to 9200
2024-02-21 16:38:16,444 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-21 16:38:16,444 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-21 16:38:16,444 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-21 16:38:16,444 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-21 16:38:16,445 INFO    MainThread:9200 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240221_163816-eteww2l4\logs\debug.log
2024-02-21 16:38:16,445 INFO    MainThread:9200 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240221_163816-eteww2l4\logs\debug-internal.log
2024-02-21 16:38:16,445 INFO    MainThread:9200 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002972902E860>
2024-02-21 16:38:16,445 INFO    MainThread:9200 [wandb_init.py:init():566] calling init triggers
2024-02-21 16:38:16,446 INFO    MainThread:9200 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'n_trees': '2', 'min_samples': '2', 'max_depth': '2', 'max_features': '0.5'}
2024-02-21 16:38:16,446 INFO    MainThread:9200 [wandb_init.py:init():591] re-initializing run, found existing run on stack: mfe1ujx5
2024-02-21 16:38:16,447 INFO    MainThread:9200 [wandb_run.py:_finish():1970] finishing run mc0c0z/RandomForest/mfe1ujx5
2024-02-21 16:38:16,447 INFO    MainThread:9200 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-21 16:38:16,448 INFO    MainThread:9200 [wandb_run.py:_restore():2193] restore
2024-02-21 16:38:16,448 INFO    MainThread:9200 [wandb_run.py:_restore():2199] restore done
2024-02-21 16:38:19,952 INFO    MainThread:9200 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-21 16:38:19,952 INFO    MainThread:9200 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-21 16:38:19,956 INFO    MainThread:9200 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-02-21 16:38:20,049 INFO    MainThread:9200 [wandb_init.py:init():616] starting backend
2024-02-21 16:38:20,049 INFO    MainThread:9200 [wandb_init.py:init():620] setting up manager
2024-02-21 16:38:20,051 INFO    MainThread:9200 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-02-21 16:38:20,052 INFO    MainThread:9200 [wandb_init.py:init():628] backend started and connected
2024-02-21 16:38:20,059 INFO    MainThread:9200 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-21 16:38:20,059 INFO    MainThread:9200 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-21 16:38:20,059 INFO    MainThread:9200 [wandb_init.py:init():720] updated telemetry
2024-02-21 16:38:20,060 INFO    MainThread:9200 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-21 16:38:21,602 INFO    MainThread:9200 [wandb_run.py:_on_init():2262] communicating current version
2024-02-21 16:38:21,778 INFO    MainThread:9200 [wandb_run.py:_on_init():2271] got version response 
2024-02-21 16:38:21,778 INFO    MainThread:9200 [wandb_init.py:init():804] starting run threads in backend
2024-02-21 16:38:21,856 INFO    MainThread:9200 [wandb_run.py:_console_start():2241] atexit reg
2024-02-21 16:38:21,856 INFO    MainThread:9200 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-21 16:38:21,856 INFO    MainThread:9200 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-21 16:38:21,857 INFO    MainThread:9200 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-21 16:38:21,857 INFO    MainThread:9200 [wandb_init.py:init():847] run started, returning control to user process
2024-02-21 16:38:21,910 INFO    MainThread:9200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-21 16:38:21,910 INFO    MainThread:9200 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-21 16:39:08,093 INFO    MainThread:9200 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-21 16:39:08,096 INFO    MainThread:9200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-21 16:39:08,097 INFO    MainThread:9200 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-21 16:39:11,798 INFO    MainThread:9200 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-21 16:39:11,811 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-21 16:39:11,811 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Configure stats pid to 9200
2024-02-21 16:39:11,811 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Loading settings from C:\Users\bdm2k\.config\wandb\settings
2024-02-21 16:39:11,811 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Loading settings from d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\settings
2024-02-21 16:39:11,812 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-21 16:39:11,812 INFO    MainThread:9200 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-21 16:39:11,812 INFO    MainThread:9200 [wandb_init.py:_log_setup():526] Logging user logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240221_163911-0indua2u\logs\debug.log
2024-02-21 16:39:11,812 INFO    MainThread:9200 [wandb_init.py:_log_setup():527] Logging internal logs to d:\2023-2024\Semester 2\Data mining\Decision tree\wandb\run-20240221_163911-0indua2u\logs\debug-internal.log
2024-02-21 16:39:11,813 INFO    MainThread:9200 [wandb_init.py:init():566] calling init triggers
2024-02-21 16:39:11,813 INFO    MainThread:9200 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'n_trees': '2', 'min_samples': '2', 'max_depth': '2', 'max_features': '0.5'}
2024-02-21 16:39:11,813 INFO    MainThread:9200 [wandb_init.py:init():591] re-initializing run, found existing run on stack: eteww2l4
2024-02-21 16:39:11,814 INFO    MainThread:9200 [wandb_run.py:_finish():1970] finishing run mc0c0z/RandomForest/eteww2l4
2024-02-21 16:39:11,816 INFO    MainThread:9200 [jupyter.py:save_history():445] not saving jupyter history
2024-02-21 16:39:11,816 INFO    MainThread:9200 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-21 16:39:11,816 INFO    MainThread:9200 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-21 16:39:11,816 INFO    MainThread:9200 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-02-21 16:39:11,817 INFO    MainThread:9200 [wandb_run.py:_restore():2193] restore
2024-02-21 16:39:11,817 INFO    MainThread:9200 [wandb_run.py:_restore():2199] restore done
2024-02-21 16:39:15,912 INFO    MainThread:9200 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-21 16:39:15,912 INFO    MainThread:9200 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-21 16:39:15,917 INFO    MainThread:9200 [wandb_run.py:_footer_sync_info():3825] logging synced files
